version: "3"
services:
  backend:
    image: dialplan-backend_dev
    container_name: backend_dev
    build:
      dockerfile: ./backend/dockerfile.dev
    volumes:
      - ./shared:/shared
      - ./backend/src:/backend/src
      - ./backend/sql:/backend/sql

  frontend:
    image: dialplan-frontend_dev
    container_name: frontend_dev
    build:
      dockerfile: ./frontend/dockerfile.dev
    volumes:
      - ./shared:/shared
      - ./frontend/src:/frontend/src
