version: "3"
services:
  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - 80:80
    volumes:
      - ./backend/nginx/dev.nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxyToServer
    restart: unless-stopped

  backend:
    depends_on:
      - frontend
    build:
      context: ./
      dockerfile: ./backend/dockerfile
    volumes:
      - webfiles:/frontend
    networks:
      - proxyToServer
    restart: unless-stopped

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/dockerfile
    volumes:
      - webfiles:/frontend

volumes:
  webfiles:

networks:
  proxyToServer:
    name: custom_proxyToServer
