FROM mcr.microsoft.com/playwright:v1.40.0-jammy

# INSTALL
COPY /shared/package*.json /shared/
WORKDIR /shared
RUN npm install

COPY /testing/package*.json /testing/
WORKDIR /testing
RUN npm install

# COPY
COPY /shared/ /shared
COPY /testing/ /testing

# RUN
CMD ["npm", "run", "playwright"]