name: E2E Tests

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:
  Playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Launch project
        run: docker-compose --env-file ./ci.env up --detach

      - name: Launch tests
        run: |
          echo "Waiting for project setup..."
          ATTEMPT=1
          CONNECTED=false
          while ! $CONNECTED; do
            echo $(curl --max-time 20 -s http://localhost:80 | grep -q "Dialplan") # temporary, debugging
            CONNECTED=$(curl --max-time 20 -s http://localhost:80 | grep -q "Dialplan" && echo true || echo false)
            echo "Server connection attempt $ATTEMPT"
            ATTEMPT=$(($ATTEMPT+1))
            sleep 3
          done
          echo "Project server is ready!"
          docker-compose -f compose.test.yaml --env-file ./ci.env up --exit-code-from playwright

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: ./testing/playwright-report
          retention-days: 7
