name: Tests

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:
  Jest:
    name: Jest (Unit & Integration)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Launch tests
        run: npm run installAll && npm run jest

  Playwright:
    name: Playwright (API & E2E)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Launch project
        run: docker-compose up --detach

      - name: Launch tests
        run: |
          ATTEMPT=1
          CONNECTED=false
          while ! $CONNECTED; do
            CONNECTED=$(curl --max-time 20 -s http://localhost:80 | grep -q "Dialplan" && echo true || echo false)
            ATTEMPT=$(($ATTEMPT+1))
            ! $CONNECTED && echo "Failed connection attempt $ATTEMPT" && sleep 3
          done
          echo "Project server is ready, launching tests..."
          docker-compose -f ./testing/compose.pw.yaml --env-file ./testing/ci.env up --exit-code-from playwright

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: ./testing/playwright-report
          retention-days: 7
